version: '3.9'
services:
    db:
        container_name: pg_container
        image: postgres
        ports:
          - "5432:5432"
    web:
        container_name: web_container
        build: .
        ports:
          - "3000:3000"
        depends_on:
          - db