version: '3.9'
services:
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  web:
    container_name: web_container
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
